site_name: XMUM XCPC Wiki
site_description: 厦门大学马来西亚分校 XCPC 知识库
site_author: Algorithm Contest Interest Group
repo_url: https://github.com/Xiamen-University-Malaysia/xcpc-wiki
repo_name: Xiamen-University-Malaysia/xcpc-wiki

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

plugins:
  - search
  - git-committers:
      repository: Xiamen-University-Malaysia/xcpc-wiki
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 简介: 
    - 首页: index.md
    - 如何贡献: contributing.md
    - 感谢: thanks.md
  - 题解: 
    - 题解简介: solution/index.md
    - ICPC 2023 济南区域赛 G: solution/2026-04-21-ICPC2023济南区域赛-GiftsfromKnowledge-zeyu10.md
  - 比赛记录: 
    - 比赛记录简介: contest/index.md
    - ICPC 2026 深圳邀请（田鸡赛码）: contest/2026-04-19-ICPC2026深圳邀请-田鸡赛码.md
  - 笔记: 
    - 笔记简介: note/index.md
  - 模板: 
    - 模板简介: template/index.md
  - 出题想法: 
    - 出题想法简介: idea/index.md
  - 资源: 
    - 资源简介: resource/index.md
  - 碎碎念: 
    - 碎碎念简介: memo/index.md
    - 追忆: memo/2026-04-20-追忆-Jayun.md
  - 杂项: 
    - 杂项简介: misc/index.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
